- name: Create an EC2 Instance for Ansible Role Testing
  hosts: localhost
  gather_facts: False
  vars:
    instance_type: t3.micro
    security_group_id: sg-0995726244f709de6
    image: ami-03e6b90c2aeee336d
    region: us-east-1
  tasks:
    - name: Launch EC2 Instance
      amazon.aws.ec2:
        count: 1
        group_id: "{{ security_group_id }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: true
        region: "{{ region }}"
        instance_tags:
          Name: ansible-role-check-instance
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      loop: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      delegate_to: "{{ item.public_dns_name }}"
      wait_for_connection:
        delay: 30
        timeout: 120
      loop: "{{ ec2.instances }}"

    - name: Set an Instance_ID Variable
      set_fact:
        INSTANCE_ID: "{{ ec2.instance_ids }}"

- name: Run Role to Test
  hosts: launched
  become: True
  gather_facts: True
  ignore_errors: True
  tasks:
    - name: set the facts per host
      set_fact:
        INSTANCE_ID: "{{hostvars['localhost']['INSTANCE_ID']}}"

    - name: Import the Role and Terminate the Instance
      block:
        - name: Import a role
          ansible.builtin.import_role:
            name: "{{role_name}}"
      always:
        - name: Terminate the Instances that were previously Launched
          delegate_to: 127.0.0.1
          amazon.aws.ec2:
            state: 'absent'
            region: us-east-1
            instance_ids: '{{ INSTANCE_ID }}'