- name: Copy MySQL Repo File
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Install MySQL
  ansible.builtin.yum:
    name:
      - mysql-community-server
      - MySQL-python
    state: installed

- name: Start MySQL
  ansible.builtin.systemd:
    name: mysqld
    state: started
    enabled: yes

- name: Check the DB Password by Collecting Information
  community.mysql.mysql_info:
      login_user: root
      login_password: RoboShop@1
  ignore_errors: yes
  register: mysql_stat

- name: Reset MySQL Password
  when: mysql_stat.failed
  block:
    - name: Grab Default Password of MySQL
      ansible.builtin.shell: grep 'temporary password' /var/log/mysqld.log | awk '{print $NF}'
      register: DEFAULT_ROOT_PASSWORD

    - name: Copy the SQL Password Reset File
      ansible.builtin.copy:
        src: rootpass.sql
        dest: /tmp/rootpass.sql

    - name: Reset MySQL Password
      ansible.builtin.shell: mysql --connect-expired-password -uroot -p"{{DEFAULT_ROOT_PASSWORD.stdout}}" </tmp/rootpass.sql

- name: Check if the Validate Password Plugin is Removed
  ansible.builtin.shell: echo 'show plugins' | mysql -uroot -pRoboShop@1 2>>${LOG_FILE} | grep validate_password
  register: PLUGIN_INFO
  ignore_errors: yes

- name: Remove Validate Password Plugin
  when: PLUGIN_INFO.rc == 0
  block:
    - name: Copy SQL File to Uninstall Password Validator Plugin
      ansible.builtin.copy:
        src: pass-validate.sql
        dest: /tmp/pass-validate.sql

    - name: Uninstall Plugin
      ansible.builtin.shell: mysql --connect-expired-password -uroot -pRoboShop@1 </tmp/pass-validate.sql




#    ```sql
#    > uninstall plugin validate_password;
#    ```
#
#    ## **Setup Needed for Application.**
#
#    As per the architecture diagram, MySQL is needed by
#
#  - Shipping Service
#
#    So we need to load that schema into the database, So those applications will detect them and run accordingly.
#
#    To download schema, Use the following command
#
#    ```bash
#    # curl -s -L -o /tmp/mysql.zip "https://github.com/roboshop-devops-project/mysql/archive/main.zip"
#    ```
#
#    Load the schema for Services.
#
#    ```bash
#    # cd /tmp
#    # unzip mysql.zip
#    # cd mysql-main
#    # mysql -u root -pRoboShop@1 <shipping.sql
#    ```